### ISSUE TITLE
Compilation error gavl_drm_fourcc_from_gavl

### ISSUE THREAD

**Issue by dr-ni** [bplaum/gavl#4]
```
/usr/bin/ld: .libs/hw_v4l2.o: in function `export_video_frame_v4l2':
hw_v4l2.c:(.text+0x288): undefined reference to `gavl_drm_fourcc_from_gavl'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:763: libgavl.la] Fehler 1
make[2]: Verzeichnis „/home/pi/gmerlin-code/gavl/gavl“ wird verlassen
make[1]: *** [Makefile:894: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/pi/gmerlin-code/gavl/gavl“ wird verlassen
make: *** [Makefile:489: all-recursive] Fehler 1
```
Here my config.log:
[config.log](https://github.com/bplaum/gavl/files/8700350/config.log)

**Comment by dr-ni** [comment]
Solution:
`sudo apt install libdrm-dev`
(should be also tested in configure)

**Comment by dr-ni** [comment]
it's now compiling without libdrm-dev but configure still does not ask for it.
is this correct?

**Comment by bplaum** [comment]
Here it says:

checking drm/drm_fourcc.h usability... no
checking drm/drm_fourcc.h presence... no
checking for drm/drm_fourcc.h... no
checking libdrm/drm_fourcc.h usability... yes
checking libdrm/drm_fourcc.h presence... yes
checking for libdrm/drm_fourcc.h... yes

The library itself is not needed, only the drm_fourcc.h header file.

**Comment by dr-ni** [comment]
ok so can beclosed?

**Comment by bplaum** [comment]
I think so.
