### ISSUE TITLE
symbols removed from libgavl but not from headers

### ISSUE THREAD

**Issue by umlaeute** [bplaum/gavl#5]
with the current git head (df05eb17b818cceab501eef68f89895e7618aded), the following symbols are no longer exported by the `libgavl.so` library, but are still found in the headers (in `include/gavl/`):

- [`gavl_msg_get_src_metadata`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/msg.h#L723)
- [`gavl_msg_set_src_metadata`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/msg.h#L720)

there's also a larger number of symbols that are still in the headers, but uncommented (or `#ifdef`ed):

- [`gavf_add_msg_stream`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L776)
- [`gavf_append_audio_stream`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L753)
- [`gavf_append_overlay_stream`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L770)
- [`gavf_append_text_stream`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L765)
- [`gavf_append_video_stream`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L759)
- [`gavf_io_set_msg_cb`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L328)
- [`gavf_open_write`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L738)
- [`gavf_packet_read_packet`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L684)
- [`gavf_select_track`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavf.h#L649)
- [`gavl_unix_socket_close`](https://github.com/bplaum/gavl/blob/9e69be196a1a67e2941dfe141a330b7593ee56f5/include/gavl/gavlsocket.h#L104)

these symbols probably should be removed from the public headers.

**Comment by bplaum** [comment]
Done.
