### ISSUE TITLE
'COPYING' is a symbolic link to a file outside this repository

### ISSUE THREAD

**Issue by umlaeute** [bplaum/gavl#6]
https://github.com/bplaum/gavl/blob/a5dd20c7af1c81e8f208c077fb0d7e88ff645d10/COPYING#L1

I guess your intention is to have the same copyright as the automake-1.16 release ( (at least for some files), as found on your disk.

However, since you have no control over what other people put in their `/usr/share/automake-1.16/COPYING` (and not even, whether this file exists in the first place), i think this is a bad idea.

please copy the copyright information verbatim into the repository.

**Comment by bplaum** [comment]
Thanks for the notice. I copied the license (GPL-2) into the repository.
